sudo: required

services:
    - docker

before_install:
    - docker build -t dominikuu/url-shortener-db ./postgres
    - docker build -t dominikuu/url-shortener-nginx ./nginx
    - docker build -t dominikuu/url-shortener-api .

script:
    - docker run dominikuu/url-shortener-api

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin
   
    - docker push dominikuu/url-shortener-nginx
    - docker push dominikuu/url-shortener-db
    - docker push dominikuu/url-shortener-api

deploy:
    provider: elasticbeanstalk
    region: ap-northeast-1
    app: url-shortener-api
    env: UrlShortenerApi-env
    bucket_name: elasticbeanstalk-ap-northeast-1-356053176662
    bucket_path: url-shortener-api
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_PASSWORD