version: '3.6'
services:
  # Nginx
  nginx:
    container_name: nginx
    build: nginx
    ports:
        - "80:80"
  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/pi-coin
      POSTGRES_DB: pi-coin
      POSTGRES_HOST: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # Backend
  pi-coin-api:
    container_name: server
    build: ./
    volumes:
      - ./:/usr/src/pi-coin-api
    command: npm start
    working_dir: /usr/src/pi-coin-api
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/pi-coin
      REDIS_URI: redis://redis:6379

volumes:
  postgres-data:
